language: node_js
node_js:
- '6'
script: npm run test-travis
env:
  global:
  - secure: Q9+xobddxjpTNQNBaJvJSUwFrvWBYt8EVn/d7AxtkzVLnZ6906jjftlmUf5CJ0cxgBTWDKsO+/SxEzHqiYrpvTKlbfqkuzIyiBNN7QcBHej7Xu5dut8uW4gL74R/PXVvAzVnSWJTadqCnLZzjyavVBg+osw6PnXxQffTXjMJKQU=
  - secure: LLkx7d0YTw1HPh8cYlW3BL79twCFMafmdatwNCWrjFWq3oLTdDqoG15kamev/nDQa+igoM/eXtodTtj9bSa7C/i19QFG3W5RO58yedoHYzzT/0htIC9X8udVuf11yHPyBSMIH8SK5Uw0SD9v6xzf8fKsuhMxBfSzHotEuIQOYrw=
  - secure: GJmAub8a0/7TpqHXzmCY9KqvglggSKiQFiRmbYggCk6gCz5TEf1okQjnFqepekYzOm6YkJItDXVxkFXjz3XGx/liqEosOpqZ0V7YmgJcI+3VjHD0VbkKHOVPncOv4xRlfVxhWZ+02gneFyulVc7xb4AC9Hn5w7uZH0I/y1N/d1M=
  - secure: gT+4Qs5MM4OMWYcvYrkTTOXephdXNouhdziJqHy/lOd4ZxpuhA39YSmRudkxjYoIF83D+b9+9Odj17dTSfOY5iHzU+QZ3y6dU2zhZB7L1Rg8sjmFsCV6qjOERvjyO1gAbN5gEI8QF+YoatX74AyySQNw4n+r9K+MdtbOiizggiQ=
  - secure: brecafurfPr32/3WjfDYiH9N8mzToLAAq9Mvi1ZNdFWbUHyMiLIIgZDgi9WfUBwjncxGhG7Yw3yLIuS8wuwltWZrIIOawMjHoyiZgb/XWMGRZdZxa6RRlycaPcSDmmLWxHcH4JXCqai9WjHPir9i2VQWPM2OZFopdMvAPw0ld04=
  - secure: SHVGFTwIukwOZS6cp/34x2XnerN/lgEQtYa19NgIQFmCzBbNgMXQ7ondx6le8eZpEJRIROvTfem4fTW62HsT1HMipPcLc8aahCUUQ6HLzVbbit9KE+Y16dqgF2wyHwCNevYitEaWmwPE9HLWpRxA9hswBdgMpGNgoE1zwmQMooQ=
  - secure: BZwr6wc56OSBiNdnwwHNDWYNo0jRbw3H850m9A0Xy46OSVLmhKAKDAjffNGDiv8k6KNY4W4Ocsk4PM/3Bws7ijAVfA6NrKp7ndRMrXS6LgxV61pIz6E9RsXmCSSIrX0fQTR5HPPGop+gIn7xCYsqwXaUuP9jyIo2kxrGHo9wQqQ=
  - secure: It/K4ganfz0YL78it8r3j8gyeDvSxAnZ7qpS4jfGnH056rtIs2ysegNkc73BnLclehDNEmxGd0c/jM7/QEnzR0/KYd/EHBuKLuNyhxrfzUZ3Crk/Hz7wCnySPDJKSYnrLcpA/nTM6xkzQAZSILLN256xXSJLt7bO2rNYQ3aBXaI=
  - secure: IggHzZSM9Z2lqHwQU/PblOwZaSYbRCINTaqJi4OxqZ6uqkteCSWyZbagasvftoS46xmFhPB5OYldcouyrEWd3Ul61rCvY2ROfhX4sIMRKMFd1ICRf9hl3R28ecxul/DhIXjhiQyRII7XNCkkN5BZ0qGhNyeAZqnaQKzPrpI4exA=
before_install:
- npm update -g npm
